dev:
  entrypoint: "mux project"
  image: gijsjan/webdev:1.1
  ports:
    - "3000:3000"
  volumes:
    - ..:/home/developer/project
    - ./tmuxinator.yml:/home/developer/.tmuxinator/project.yml
    - ~/.ssh:/home/developer/.ssh